import legalitLogoImg from "@assets/logo_legalit_cropped.png";
import legalitLogoSymbol from "@assets/logo_legalit_cropped_(1)_1771133031977.png";
import legalitLogoText from "@assets/logo_legalit_cropped_1771133031978.png";

export const legalitLogo = legalitLogoImg;
export const legalitLogoDark = legalitLogoImg;
export const legalitLogoIcon = legalitLogoSymbol;
export const legalitLogoWordmark = legalitLogoText;

export const stats = [
  { label: "Anni di Esperienza", value: 15, suffix: "" },
  { label: "Professionisti", value: 30, suffix: "" },
  { label: "Clienti Assistiti", value: 5340, suffix: "+" },
  { label: "Casi Risolti", value: 7000, suffix: "+" },
];

export const practiceAreas = [
  {
    id: "diritto-civile-commerciale",
    title: "Diritto Civile e Commerciale",
    items: [
      "Diritto civile generale",
      "Obbligazioni e contratti",
      "Responsabilità civile",
      "Assicurazione e risarcimento del danno",
      "Diritto dei consumatori",
      "Famiglia e successioni",
      "Condominio e locazioni",
      "Diritto Commerciale e societario",
      "Fallimento ed altre procedure concorsuali",
      "Procedura civile",
      "Esecuzioni mobiliari ed immobiliari",
    ],
  },
  {
    id: "diritto-penale",
    title: "Diritto Penale e Penale d'Impresa",
    items: [
      "Reati contro la persona",
      "Reati contro il patrimonio",
      "Reati contro la Pubblica Amministrazione",
      "Colpa medica",
      "Reati di falso",
      "Reati societari",
      "Reati fallimentari",
      "Reati tributari",
      "Reati ambientali ed edilizi",
      "Reati stradali",
      "Reati in materia di stupefacenti",
      "Reati informatici",
      "Reati in materia di immigrazione",
      "Responsabilità degli enti ex d.lgs. 231/01",
      "Procedura penale",
    ],
  },
  {
    id: "diritto-lavoro",
    title: "Diritto del Lavoro, Previdenziale e Relazioni Industriali",
    items: [
      "Diritto del lavoro generale",
      "Licenziamenti",
      "Contratti di lavoro",
      "Mobbing",
      "Diritto sindacale",
      "Previdenza sociale",
      "Processo del lavoro",
    ],
  },
  {
    id: "diritto-amministrativo",
    title: "Diritto Amministrativo, Enti locali e Appalti Pubblici",
    items: [
      "Diritto amministrativo",
      "Appalti pubblici",
      "Edilizia e urbanistica",
      "Enti locali",
      "Giustizia amministrativa",
    ],
  },
  {
    id: "corporate-compliance",
    title: "Corporate Compliance, Internal Investigations e Responsabilità degli Enti ex d.lgs. 231/01",
    items: [
      "Modelli organizzativi 231",
      "Investigazioni interne",
      "Whistleblowing",
      "Anticorruzione",
      "Antiriciclaggio",
    ],
  },
  {
    id: "crisi-impresa",
    title: "Crisi d'Impresa e Ristrutturazioni",
    items: [
      "Concordato preventivo",
      "Accordi di ristrutturazione",
      "Piani di risanamento",
      "Liquidazione giudiziale",
      "Composizione negoziata della crisi",
    ],
  },
  {
    id: "diritto-societario-ma",
    title: "Diritto Societario ed M&A",
    items: [
      "Operazioni di M&A",
      "Due diligence",
      "Contratti di acquisizione",
      "Patti parasociali",
      "Joint venture",
      "Governance societaria",
    ],
  },
  {
    id: "diritto-sanitario",
    title: "Diritto Sanitario, Responsabilità Medica & Life Sciences",
    items: [
      "Responsabilità medica",
      "Diritto farmaceutico",
      "Dispositivi medici",
      "Sanità pubblica e privata",
      "Contenzioso sanitario",
    ],
  },
  {
    id: "affari-regolatori",
    title: "Affari Regolatori & Public Affairs",
    items: [
      "Rapporti istituzionali",
      "Regulatory affairs",
      "Lobbying",
      "Compliance regolatoria",
    ],
  },
  {
    id: "diritto-sport",
    title: "Diritto dello Sport",
    items: [
      "Contrattualistica sportiva",
      "Giustizia sportiva",
      "Antidoping",
      "Diritti TV e sponsorizzazioni",
    ],
  },
  {
    id: "recupero-crediti",
    title: "Recupero crediti, NPL e procedure esecutive",
    items: [
      "Recupero crediti stragiudiziale",
      "Procedure esecutive mobiliari",
      "Procedure esecutive immobiliari",
      "NPL e crediti deteriorati",
      "Pignoramenti",
    ],
  },
  {
    id: "diritto-assicurazioni",
    title: "Diritto delle Assicurazioni",
    items: [
      "Contratti assicurativi",
      "Risarcimento danni",
      "RC Auto",
      "Responsabilità professionale",
      "Contenzioso assicurativo",
    ],
  },
  {
    id: "real-estate",
    title: "Real Estate",
    items: [
      "Compravendite immobiliari",
      "Locazioni commerciali",
      "Sviluppo immobiliare",
      "Due diligence immobiliare",
      "Contenzioso immobiliare",
    ],
  },
  {
    id: "tutela-patrimoni",
    title: "Tutela dei Patrimoni, Famiglia, Minori & Successioni",
    items: [
      "Pianificazione patrimoniale",
      "Trust e protezione patrimoniale",
      "Diritto di famiglia",
      "Tutela dei minori",
      "Successioni e testamenti",
    ],
  },
  {
    id: "ambiente-energia",
    title: "Diritto dell'Ambiente ed Energia",
    items: [
      "Autorizzazioni ambientali",
      "Bonifiche",
      "Energie rinnovabili",
      "Efficienza energetica",
      "Contenzioso ambientale",
    ],
  },
  {
    id: "responsabilita-contabile",
    title: "Responsabilità amministrativo contabile",
    items: [
      "Danno erariale",
      "Giudizio contabile",
      "Responsabilità amministrativa",
      "Corte dei Conti",
    ],
  },
  {
    id: "privacy-cybersecurity",
    title: "Intelligenza Artificiale, Privacy & Cybersecurity",
    items: [
      "GDPR e privacy",
      "Data protection",
      "Cybersecurity",
      "Intelligenza artificiale",
      "Protezione dati personali",
    ],
  },
  {
    id: "banking-finance",
    title: "Banking & Finance",
    items: [
      "Contratti bancari",
      "Finanziamenti",
      "Garanzie",
      "Contenzioso bancario",
      "Usura e anatocismo",
    ],
  },
  {
    id: "diritto-tributario",
    title: "Diritto Tributario",
    items: [
      "Contenzioso tributario",
      "Accertamenti fiscali",
      "Pianificazione fiscale",
      "Reati tributari",
    ],
  },
];

export const offices = [
  {
    id: "roma",
    city: "Roma",
    address: "Via Filippo Corridoni, 19",
    cap: "00195 RM",
    phone: "06 3213911",
    fax: "06 32609928",
    email: "roma@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2969.4!2d12.4635!3d41.9091!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132f6106b7a5e96f%3A0x8c9a9a5e0c8d7b5a!2sVia%20Filippo%20Corridoni%2C%2019%2C%2000195%20Roma%20RM!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/RbJzN2n1FkJ9LH9k8",
  },
  {
    id: "milano",
    city: "Milano",
    address: "Piazzetta Guastalla, 3",
    cap: "20122 MI",
    phone: "02 83424497",
    fax: "02 83424493",
    email: "milano@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2798.2!2d9.1988!3d45.4598!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4786c6a9d7b8c5e7%3A0x8a9b0c1d2e3f4a5b!2sPiazzetta%20Guastalla%2C%203%2C%2020122%20Milano%20MI!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/ZGqzRjZr2QFbvsbL6",
  },
  {
    id: "palermo",
    city: "Palermo",
    address: "Via della Libertà, 39",
    cap: "90139 PA",
    phone: "091 7781494",
    fax: "091 7781493",
    email: "palermo@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3048.3!2d13.3492!3d38.1281!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1319e5c6d7e8f9a0%3A0x0123456789abcdef!2sVia%20della%20Libert%C3%A0%2C%2039%2C%2090139%20Palermo%20PA!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/2Xn2NDqqBgYMZrKz5",
  },
  {
    id: "latina",
    city: "Latina",
    address: "Viale Le Corbusier scala A",
    cap: "04100 LT",
    phone: "0773 621157",
    fax: "",
    email: "latina@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2982.5!2d12.9008!3d41.4675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x13251f0a1b2c3d4e%3A0x5f6a7b8c9d0e1f2a!2sViale%20Le%20Corbusier%2C%2004100%20Latina%20LT!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/LatinaLegalit",
  },
];

export const professionals = [
  // 1. Francesco Vaccaro - Managing Partner
  {
    id: "1",
    name: "Avv. Francesco Vaccaro",
    title: "Managing Partner",
    role: "Managing Partner",
    specializations: ["diritto-penale", "corporate-compliance", "crisi-impresa", "diritto-societario-ma", "diritto-sanitario", "affari-regolatori", "diritto-sport"],
    office: "Roma",
    email: "f.vaccaro@legalit.it",
    pec: "francescovaccaro@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-francesco-vaccaro.jpg",
  },
  // 2. Renato Piero Biasci - Partner
  {
    id: "2",
    name: "Avv. Renato Piero Biasci",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "diritto-assicurazioni", "crisi-impresa", "real-estate", "tutela-patrimoni"],
    office: "Roma",
    email: "r.biasci@legalit.it",
    pec: "renatopierobiasci@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-renato-piero-biasci.jpg",
  },
  // 3. Pasquale Passalacqua - Partner
  {
    id: "3",
    name: "Prof. Avv. Pasquale Passalacqua",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "p.passalacqua@legalit.it",
    pec: "pasqualepassalacqua@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/prof-avv-pasquale-passalacqua.jpg",
  },
  // 4. Fabiana Liberati - Partner
  {
    id: "4",
    name: "Avv. Fabiana Liberati",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "f.liberati@legalit.it",
    pec: "fabianaliberati@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-fabiana-liberati.jpg",
    linkedin: "https://www.linkedin.com/in/fabiana-liberati-392a558a/",
  },
  // 5. Luigi Passalacqua - Partner
  {
    id: "5",
    name: "Avv. Luigi Passalacqua",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "l.passalacqua@legalit.it",
    pec: "luigipassalacqua@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese", "Spagnolo"],
    imageUrl: "/attached_assets/avv-luigi-passalacqua.jpg",
  },
  // 6. Giorgio Ialongo - Partner
  {
    id: "6",
    name: "Avv. Giorgio Ialongo",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "diritto-assicurazioni", "crisi-impresa"],
    office: "Roma",
    email: "g.ialongo@legalit.it",
    pec: "giorgioialongo@pec.it",
    phone: "+39 0774 381495",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 7. Alessandro Santomauro - Partner
  {
    id: "7",
    name: "Avv. Alessandro Santomauro",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "diritto-societario-ma"],
    office: "Roma",
    email: "a.santomauro@legalit.it",
    pec: "alessandrosantomauro@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-alessandro-santomauro.jpg",
  },
  // 8. Francesco Pastorello - Partner
  {
    id: "8",
    name: "Avv. Francesco Pastorello",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-penale", "corporate-compliance", "diritto-sanitario"],
    office: "Roma",
    email: "f.pastorello@legalit.it",
    pec: "francescopastorello@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
  },
  // 9. Bernardo Fabbri - Partner
  {
    id: "9",
    name: "Avv. Bernardo Fabbri",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-penale", "corporate-compliance", "privacy-cybersecurity", "tutela-patrimoni"],
    office: "Roma",
    email: "b.fabbri@legalit.it",
    pec: "bernardofabbri@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
  },
  // 10. Carmine Andrea Silvestri - Partner
  {
    id: "10",
    name: "Avv. Carmine Andrea Silvestri",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-societario-ma", "diritto-civile-commerciale", "recupero-crediti", "crisi-impresa", "diritto-penale"],
    office: "Roma",
    email: "a.silvestri@legalit.it",
    pec: "a_silvestri@legalmail.it",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
  },
  // 11. Sonja Puglionisi - Partner
  {
    id: "11",
    name: "Avv. Sonja Puglionisi",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "s.puglionisi@legalit.it",
    pec: "sonjapuglionisi@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
  },
  // 12. Giovanni Puntarello - Partner (Palermo)
  {
    id: "12",
    name: "Avv. Giovanni Puntarello",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-amministrativo", "ambiente-energia", "responsabilita-contabile", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "g.puntarello@legalit.it",
    pec: "giovannipuntarello@pec.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-giovanni-puntarello.jpg",
  },
  // 15. Carmelina Adamo - Partner (Milano)
  {
    id: "15",
    name: "Avv. Carmelina Adamo",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-penale", "diritto-civile-commerciale"],
    office: "Milano",
    email: "c.adamo@legalit.it",
    pec: "carmelina.adamo@milano.pecavvocati.it",
    phone: "+39 02 83424497",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 16. Elena Preite - Partner (Milano)
  {
    id: "16",
    name: "Avv. Elena Preite",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "diritto-lavoro"],
    office: "Milano",
    email: "e.preite@legalit.it",
    pec: "elena.preite@milano.pecavvocati.it",
    phone: "+39 02 83424497",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 17. Tommaso Giannini - Partner (Milano)
  {
    id: "17",
    name: "Avv. Tommaso Giannini",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "diritto-lavoro"],
    office: "Milano",
    email: "t.giannini@legalit.it",
    pec: "tommaso.giannini@milano.pecavvocati.it",
    phone: "+39 02 83424497",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 18. Stefano Cherti - Of Counsel
  {
    id: "18",
    name: "Prof. Avv. Stefano Cherti",
    title: "Of Counsel",
    role: "Of Counsel",
    specializations: ["banking-finance", "diritto-assicurazioni", "diritto-civile-commerciale", "diritto-societario-ma", "recupero-crediti", "diritto-sanitario", "tutela-patrimoni"],
    office: "Roma",
    email: "s.cherti@legalit.it",
    pec: "stefanocherti@pec.it",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
  },
  // 19. Laura Stefanelli - Of Counsel
  {
    id: "19",
    name: "Avv. Laura Stefanelli",
    title: "Of Counsel",
    role: "Of Counsel",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "tutela-patrimoni"],
    office: "Roma",
    email: "l.stefanelli@legalit.it",
    pec: "l.stefanelli@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 20. Claudio Iafrate - Senior Associate
  {
    id: "20",
    name: "Avv. Claudio Iafrate",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "diritto-assicurazioni", "crisi-impresa", "real-estate", "tutela-patrimoni"],
    office: "Roma",
    email: "c.iafrate@legalit.it",
    pec: "c.iafrate@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 21. Flavia Cracchiolo - Senior Associate
  {
    id: "21",
    name: "Avv. Flavia Cracchiolo",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "f.cracchiolo@legalit.it",
    pec: "f.cracchiolo@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 22. Lorenzo Ferrara - Senior Associate
  {
    id: "22",
    name: "Avv. Lorenzo Ferrara",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-penale", "corporate-compliance", "diritto-tributario", "crisi-impresa", "diritto-assicurazioni", "diritto-sanitario"],
    office: "Roma",
    email: "l.ferrara@legalit.it",
    pec: "l.ferrara@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 23. Sabrina Causa - Senior Associate (Palermo)
  {
    id: "23",
    name: "Avv. Sabrina Causa",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "s.causa@legalit.it",
    pec: "sabrinacausa@pecavvpa.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-sabrina-causa.jpg",
  },
  // 24. Paola Saladino - Senior Associate (Palermo)
  {
    id: "24",
    name: "Avv. Paola Saladino",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "p.saladino@legalit.it",
    pec: "paolasaladino@pecavvpa.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-paola-saladino.jpg",
  },
  // 25. Luciana Maria Russo - Senior Associate (Palermo)
  {
    id: "25",
    name: "Avv. Luciana Maria Russo",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "l.russo@legalit.it",
    pec: "lucianarusso0605@pec.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-luciana-maria-russo.jpg",
  },
  // 26. Calogero Gianluca Rizzuto - Senior Associate (Palermo)
  {
    id: "26",
    name: "Avv. Calogero Gianluca Rizzuto",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-penale", "corporate-compliance", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "c.rizzuto@legalit.it",
    pec: "calogerorizzuto@pecavvpa.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 27. Riccardo Costa - Associate (Palermo)
  {
    id: "27",
    name: "Avv. Riccardo Costa",
    title: "Associate",
    role: "Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "r.costa@legalit.it",
    pec: "costa.riccard@pec.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-riccardo-costa.jpg",
  },
  // 28. Alessandro Maria Miliziano - Associate (Palermo)
  {
    id: "28",
    name: "Avv. Alessandro Maria Miliziano",
    title: "Associate",
    role: "Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "a.miliziano@legalit.it",
    pec: "",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-alessandro-miliziano.jpg",
  },
  // 29. Marco Pauletti - Trainee
  {
    id: "29",
    name: "Dott. Marco Pauletti",
    title: "Trainee",
    role: "Trainee",
    specializations: ["diritto-penale", "corporate-compliance"],
    office: "Roma",
    email: "m.pauletti@legalit.it",
    pec: "m.pauletti@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
  },
  // 30. Angela Martina Tortorici - Trainee (Palermo)
  {
    id: "30",
    name: "Dott. Angela Martina Tortorici",
    title: "Trainee",
    role: "Trainee",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "m.tortorici@legalit.it",
    pec: "",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-angela-martina-tortorici.jpg",
  },
];

export const values = [
  {
    title: "Eccellenza Legale",
    description: "Assistenza legale di qualità superiore basata su competenza ed esperienza pluridecennale.",
  },
  {
    title: "Approccio Multidisciplinare",
    description: "Team di professionisti specializzati in diverse aree del diritto per soluzioni complete.",
  },
  {
    title: "Integrità e Trasparenza",
    description: "Rapporto di fiducia costruito sulla chiarezza e onestà professionale.",
  },
  {
    title: "Innovazione Continua",
    description: "Aggiornamento costante su normative e tecnologie per servizi all'avanguardia.",
  },
];
