import legalitLogoImg from "@assets/logo_legalit_cropped.png";
import legalitLogoSymbol from "@assets/logo_legalit_cropped_(1)_1771133031977.png";
import legalitLogoText from "@assets/logo_legalit_cropped_1771133031978.png";

export const legalitLogo = legalitLogoImg;
export const legalitLogoDark = legalitLogoImg;
export const legalitLogoIcon = legalitLogoSymbol;
export const legalitLogoWordmark = legalitLogoText;

export const stats = [
  { label: "Anni di Esperienza", value: 15, suffix: "" },
  { label: "Professionisti", value: 30, suffix: "" },
  { label: "Clienti Assistiti", value: 5340, suffix: "+" },
  { label: "Casi Risolti", value: 7000, suffix: "+" },
];

export const practiceAreas = [
  {
    id: "diritto-civile-commerciale",
    title: "Diritto Civile e Commerciale",
    items: [
      "Diritto civile generale",
      "Obbligazioni e contratti",
      "Responsabilità civile",
      "Assicurazione e risarcimento del danno",
      "Diritto dei consumatori",
      "Famiglia e successioni",
      "Condominio e locazioni",
      "Diritto Commerciale e societario",
      "Fallimento ed altre procedure concorsuali",
      "Procedura civile",
      "Esecuzioni mobiliari ed immobiliari",
    ],
  },
  {
    id: "diritto-penale",
    title: "Diritto Penale e Reati d'Impresa",
    items: [
      "Reati contro la persona",
      "Reati contro il patrimonio",
      "Reati contro la Pubblica Amministrazione",
      "Colpa medica",
      "Reati di falso",
      "Reati societari",
      "Reati fallimentari",
      "Reati tributari",
      "Reati ambientali ed edilizi",
      "Reati stradali",
      "Reati in materia di stupefacenti",
      "Reati informatici",
      "Reati in materia di immigrazione",
      "Responsabilità degli enti ex d.lgs. 231/01",
      "Procedura penale",
    ],
  },
  {
    id: "diritto-lavoro",
    title: "Diritto del Lavoro, Previdenza e Relazioni Industriali",
    items: [
      "Diritto del lavoro generale",
      "Licenziamenti",
      "Contratti di lavoro",
      "Mobbing",
      "Diritto sindacale",
      "Previdenza sociale",
      "Processo del lavoro",
    ],
  },
  {
    id: "diritto-amministrativo",
    title: "Diritto Amministrativo, Enti locali e Appalti Pubblici",
    items: [
      "Diritto amministrativo",
      "Appalti pubblici",
      "Edilizia e urbanistica",
      "Enti locali",
      "Giustizia amministrativa",
    ],
  },
  {
    id: "corporate-compliance",
    title: "Corporate Compliance, Internal Investigations e Responsabilità degli Enti ex D.Lgs. 231/01",
    items: [
      "Modelli organizzativi 231",
      "Investigazioni interne",
      "Whistleblowing",
      "Anticorruzione",
      "Antiriciclaggio",
    ],
  },
  {
    id: "crisi-impresa",
    title: "Crisi d'Impresa e Ristrutturazioni",
    items: [
      "Concordato preventivo",
      "Accordi di ristrutturazione",
      "Piani di risanamento",
      "Liquidazione giudiziale",
      "Composizione negoziata della crisi",
    ],
  },
  {
    id: "diritto-societario-ma",
    title: "Diritto Societario ed M&A",
    items: [
      "Operazioni di M&A",
      "Due diligence",
      "Contratti di acquisizione",
      "Patti parasociali",
      "Joint venture",
      "Governance societaria",
    ],
  },
  {
    id: "diritto-sanitario",
    title: "Diritto Sanitario, Responsabilità Medica & Life Sciences",
    items: [
      "Responsabilità medica",
      "Diritto farmaceutico",
      "Dispositivi medici",
      "Sanità pubblica e privata",
      "Contenzioso sanitario",
    ],
  },
  {
    id: "affari-regolatori",
    title: "Regulatory & Public Affairs",
    items: [
      "Rapporti istituzionali",
      "Regulatory affairs",
      "Lobbying",
      "Compliance regolatoria",
    ],
  },
  {
    id: "diritto-sport",
    title: "Diritto dello Sport",
    items: [
      "Contrattualistica sportiva",
      "Giustizia sportiva",
      "Antidoping",
      "Diritti TV e sponsorizzazioni",
    ],
  },
  {
    id: "recupero-crediti",
    title: "Gestione del Credito, NPL e Procedure Esecutive",
    items: [
      "Gestione crediti stragiudiziale",
      "Procedure esecutive mobiliari",
      "Procedure esecutive immobiliari",
      "NPL e crediti deteriorati",
      "Pignoramenti",
    ],
  },
  {
    id: "diritto-assicurazioni",
    title: "Diritto delle Assicurazioni e Responsabilità Civile",
    items: [
      "Contratti assicurativi",
      "Risarcimento danni",
      "RC Auto",
      "Responsabilità professionale",
      "Contenzioso assicurativo",
    ],
  },
  {
    id: "real-estate",
    title: "Real Estate",
    items: [
      "Compravendite immobiliari",
      "Locazioni commerciali",
      "Sviluppo immobiliare",
      "Due diligence immobiliare",
      "Contenzioso immobiliare",
    ],
  },
  {
    id: "tutela-patrimoni",
    title: "Tutela dei Patrimoni, Famiglia e Successioni",
    items: [
      "Pianificazione patrimoniale",
      "Trust e protezione patrimoniale",
      "Diritto di famiglia",
      "Successioni e testamenti",
    ],
  },
  {
    id: "ambiente-energia",
    title: "Diritto dell'Ambiente ed Energia",
    items: [
      "Autorizzazioni ambientali",
      "Bonifiche",
      "Energie rinnovabili",
      "Efficienza energetica",
      "Contenzioso ambientale",
    ],
  },
  {
    id: "responsabilita-contabile",
    title: "Responsabilità Amministrativo-Contabile",
    items: [
      "Danno erariale",
      "Giudizio contabile",
      "Responsabilità amministrativa",
      "Corte dei Conti",
    ],
  },
  {
    id: "privacy-cybersecurity",
    title: "Intelligenza Artificiale, Privacy & Cybersecurity",
    items: [
      "GDPR e privacy",
      "Data protection",
      "Cybersecurity",
      "Intelligenza artificiale",
      "Protezione dati personali",
    ],
  },
  {
    id: "banking-finance",
    title: "Banking & Finance",
    items: [
      "Contratti bancari",
      "Finanziamenti",
      "Garanzie",
      "Contenzioso bancario",
      "Usura e anatocismo",
    ],
  },
  {
    id: "diritto-tributario",
    title: "Diritto Tributario",
    items: [
      "Contenzioso tributario",
      "Accertamenti fiscali",
      "Pianificazione fiscale",
      "Reati tributari",
    ],
  },
  {
    id: "terzo-settore",
    title: "Terzo Settore e No Profit",
    items: [
      "Enti del terzo settore",
      "Associazioni e fondazioni",
      "ONLUS e imprese sociali",
      "Governance e compliance no profit",
    ],
  },
];

export const offices = [
  {
    id: "roma",
    city: "Roma",
    address: "Via Filippo Corridoni, 19",
    cap: "00195 RM",
    phone: "06 3213911",
    fax: "06 32609928",
    email: "roma@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2969.4!2d12.4635!3d41.9091!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132f6106b7a5e96f%3A0x8c9a9a5e0c8d7b5a!2sVia%20Filippo%20Corridoni%2C%2019%2C%2000195%20Roma%20RM!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/RbJzN2n1FkJ9LH9k8",
  },
  {
    id: "milano",
    city: "Milano",
    address: "Piazzetta Guastalla, 3",
    cap: "20122 MI",
    phone: "02 83424497",
    fax: "02 83424493",
    email: "milano@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2798.2!2d9.1988!3d45.4598!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4786c6a9d7b8c5e7%3A0x8a9b0c1d2e3f4a5b!2sPiazzetta%20Guastalla%2C%203%2C%2020122%20Milano%20MI!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/ZGqzRjZr2QFbvsbL6",
  },
  {
    id: "palermo",
    city: "Palermo",
    address: "Via della Libertà, 39",
    cap: "90139 PA",
    phone: "091 7781494",
    fax: "091 7781493",
    email: "palermo@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3048.3!2d13.3492!3d38.1281!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1319e5c6d7e8f9a0%3A0x0123456789abcdef!2sVia%20della%20Libert%C3%A0%2C%2039%2C%2090139%20Palermo%20PA!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/2Xn2NDqqBgYMZrKz5",
  },
  {
    id: "latina",
    city: "Latina",
    address: "Viale Le Corbusier scala A",
    cap: "04100 LT",
    phone: "0773 621157",
    fax: "",
    email: "latina@legalit.it",
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2982.5!2d12.9008!3d41.4675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x13251f0a1b2c3d4e%3A0x5f6a7b8c9d0e1f2a!2sViale%20Le%20Corbusier%2C%2004100%20Latina%20LT!5e0!3m2!1sit!2sit!4v1699999999999!5m2!1sit!2sit",
    googleMapsLink: "https://goo.gl/maps/LatinaLegalit",
  },
];

export const professionals = [
  {
    id: "1",
    name: "Avv. Francesco Vaccaro",
    title: "Managing Partner",
    role: "Managing Partner",
    specializations: ["diritto-penale", "corporate-compliance", "crisi-impresa", "diritto-societario-ma", "diritto-sanitario", "affari-regolatori", "diritto-sport"],
    office: "Roma",
    email: "f.vaccaro@legalit.it",
    pec: "francescovaccaro@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-francesco-vaccaro.jpg",
    orderIndex: 1,
  },
  {
    id: "4",
    name: "Avv. Fabiana Liberati",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "f.liberati@legalit.it",
    pec: "",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-fabiana-liberati.jpg",
    linkedin: "https://www.linkedin.com/in/fabiana-liberati-392a558a/",
    orderIndex: 2,
  },
  {
    id: "3",
    name: "Prof. Avv. Pasquale Passalacqua",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "p.passalacqua@legalit.it",
    pec: "pasqualepassalacqua@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/prof-avv-pasquale-passalacqua.jpg",
    orderIndex: 3,
  },
  {
    id: "5",
    name: "Avv. Luigi Passalacqua",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "l.passalacqua@legalit.it",
    pec: "luigipassalacqua@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    fullBio: "Luigi Passalacqua si occupa prevalentemente di diritto del lavoro, sindacale e della previdenza sociale, sia in ambito di consulenza stragiudiziale (contrattualistica e negoziazione; gestione del rapporto di lavoro, anche di natura dirigenziale; sicurezza del lavoro; assistenza nelle procedure di riorganizzazione e trasferimento d'azienda, riduzione del personale, outsourcing, dismissione o acquisizione di attività), sia di assistenza giudiziale.\n\nDopo un'esperienza di diversi anni presso uno studio legale italiano operante a livello internazionale, dal 2010 è partner fondatore dello Studio.\n\nÈ avvocato fiduciario e consulente di numerosi enti e società pubbliche e private, enti locali ed associazioni di categoria, nonché arbitro in procedure di conciliazione.\n\nLaureato in Giurisprudenza presso l'Università di Roma Tre, ha poi conseguito il diploma presso il Master di secondo livello in discipline del lavoro, sindacali e della sicurezza sociale presso l'Università Tor Vergata di Roma e il diploma della Scuola di specializzazione per le professioni legali dell'Università di Roma Tre.\n\nÈ iscritto all'Ordine degli Avvocati di Roma ed è socio dell'AGI (Avvocati Giuslavoristi Italiani) e di AIDLaSS Forense (Associazione italiana forense di Diritto del Lavoro e della Sicurezza sociale).\n\nParla l'inglese e lo spagnolo, appresi durante diversi periodi di permanenza all'estero.",
    education: ["Laurea in Giurisprudenza - Università di Roma Tre", "Master di secondo livello in discipline del lavoro - Università Tor Vergata", "Scuola di specializzazione per le professioni legali - Università di Roma Tre"],
    languages: ["Italiano", "Inglese", "Spagnolo"],
    imageUrl: "/attached_assets/avv-luigi-passalacqua.jpg",
    orderIndex: 4,
  },
  {
    id: "2",
    name: "Avv. Renato Piero Biasci",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "diritto-assicurazioni", "crisi-impresa", "real-estate", "tutela-patrimoni"],
    office: "Roma",
    email: "r.biasci@legalit.it",
    pec: "renatopierobiasci@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-renato-piero-biasci.jpg",
    orderIndex: 5,
  },
  {
    id: "6",
    name: "Avv. Giorgio Ialongo",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "diritto-assicurazioni", "crisi-impresa"],
    office: "Roma",
    email: "g.ialongo@legalit.it",
    pec: "giorgioialongo@pec.it",
    phone: "+39 0774 381495",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/a26569b4-aaef-4298-84cd-714dc18648bf_1771450876374.png",
    orderIndex: 6,
  },
  {
    id: "12",
    name: "Avv. Giovanni Puntarello",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-amministrativo", "ambiente-energia", "responsabilita-contabile", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "g.puntarello@legalit.it",
    pec: "giovannipuntarello@pec.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-giovanni-puntarello.jpg",
    orderIndex: 7,
  },
  {
    id: "7",
    name: "Avv. Alessandro Santomauro",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "diritto-societario-ma"],
    office: "Roma",
    email: "a.santomauro@legalit.it",
    pec: "alessandrosantomauro@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "/attached_assets/avv-alessandro-santomauro.jpg",
    orderIndex: 8,
  },
  {
    id: "8",
    name: "Avv. Francesco Pastorello",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-penale", "corporate-compliance", "diritto-sanitario"],
    office: "Roma",
    email: "f.pastorello@legalit.it",
    pec: "francescopastorello@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
    orderIndex: 9,
  },
  {
    id: "9",
    name: "Avv. Bernardo Fabbri",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-penale", "corporate-compliance", "privacy-cybersecurity", "tutela-patrimoni"],
    office: "Roma",
    email: "b.fabbri@legalit.it",
    pec: "bernardofabbri@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
    orderIndex: 10,
  },
  {
    id: "10",
    name: "Avv. Carmine Andrea Silvestri",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-societario-ma", "diritto-civile-commerciale", "recupero-crediti", "crisi-impresa", "diritto-penale"],
    office: "Roma",
    email: "a.silvestri@legalit.it",
    pec: "a_silvestri@legalmail.it",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
    orderIndex: 11,
  },
  {
    id: "15",
    name: "Avv. Carmelina Adamo",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-penale", "diritto-civile-commerciale"],
    office: "Milano",
    email: "c.adamo@legalit.it",
    pec: "carmelina.adamo@milano.pecavvocati.it",
    phone: "+39 02 83424497",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
    orderIndex: 12,
  },
  {
    id: "16",
    name: "Avv. Elena Preite",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "diritto-lavoro"],
    office: "Milano",
    email: "e.preite@legalit.it",
    pec: "elena.preite@milano.pecavvocati.it",
    phone: "+39 02 83424497",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
    orderIndex: 13,
  },
  {
    id: "17",
    name: "Avv. Tommaso Giannini",
    title: "Partner",
    role: "Partner",
    specializations: ["diritto-civile-commerciale", "diritto-lavoro"],
    office: "Milano",
    email: "t.giannini@legalit.it",
    pec: "tommaso.giannini@milano.pecavvocati.it",
    phone: "+39 02 83424497",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
    orderIndex: 14,
  },
  {
    id: "18",
    name: "Prof. Avv. Stefano Cherti",
    title: "Of Counsel",
    role: "Of Counsel",
    specializations: ["banking-finance", "diritto-assicurazioni", "diritto-civile-commerciale", "diritto-societario-ma", "recupero-crediti", "diritto-sanitario", "tutela-patrimoni"],
    office: "Roma",
    email: "s.cherti@legalit.it",
    pec: "stefanocherti@pec.it",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
    orderIndex: 15,
  },
  {
    id: "19",
    name: "Avv. Laura Stefanelli",
    title: "Of Counsel",
    role: "Of Counsel",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "tutela-patrimoni"],
    office: "Roma",
    email: "l.stefanelli@legalit.it",
    pec: "l.stefanelli@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-laura-stefanelli.jpg",
    orderIndex: 16,
  },
  {
    id: "20",
    name: "Avv. Claudio Iafrate",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-civile-commerciale", "recupero-crediti", "diritto-assicurazioni", "crisi-impresa", "real-estate", "tutela-patrimoni"],
    office: "Roma",
    email: "c.iafrate@legalit.it",
    pec: "c.iafrate@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    fullBio: "Claudio Iafrate è avvocato del Foro di Roma iscritto all'Albo dell'Ordine degli Avvocati di Roma dal 2016.\n\nOpera nel diritto civile con un'impostazione orientata alla gestione del contenzioso e del rischio legale per privati, imprese e professionisti. La sua attività si concentra sulla consulenza e contrattualistica in ambito societario e assicurativo, nonché sul recupero crediti ed esecuzioni mobiliari e immobiliari, con attenzione agli aspetti concreti che incidono su tempi, costi e risultati.\n\nÈ iscritto presso le liste dei Professionisti Delegati alle vendite immobiliari e Custode Giudiziario presso il Tribunale di Roma nonché è inserito nelle liste dei difensori d'ufficio presso il Tribunale di Roma.\n\nIn ambito societario segue la redazione e negoziazione dei contratti commerciali e assiste nelle controversie tra soci, società e controparti, intervenendo sia nella fase preventiva (assetto dei rapporti e clausole di tutela) sia nella fase patologica (inadempimenti, responsabilità e azioni giudiziali). In ambito assicurativo affianca il cliente nella gestione di vertenze relative a coperture e sinistri, curando l'istruttoria e trattative e, quando necessario, l'azione giudiziale.\n\nNel settore esecutivo e immobiliare integra la dimensione contrattuale con quella processuale, assistendo nella contrattualistica collegata a diritti reali e alle vicende dell'immobile e, in caso di inadempimento, nella tutela per il rilascio e il recupero del bene. Segue inoltre le procedure esecutive e le questioni incidentali che possono emergere nel corso della procedura. Si occupa di contenzioso condominiale, affiancando amministratori, condomìni e singoli partecipanti nella gestione e risoluzione delle controversie.\n\nAffianca a tali ambiti una competenza specifica in diritto d'autore, maturata in consulenze per artisti musicali e per produzioni cinematografiche e audiovisive, con particolare riguardo alla contrattualistica, alle licenze e alla tutela dei diritti di utilizzazione economica. Svolge inoltre consulenza contrattuale per lo sviluppo di app e siti web, predisponendo accordi con sviluppatori e fornitori e la documentazione essenziale di esercizio.\n\nNel 2013 ha conseguito la Laurea presso l'Università degli Studi di Roma Tre con tesi in diritto cinese (\"L'arbitrato nella Repubblica Popolare Cinese\"), approfondendo i profili procedurali delle ADR nel contesto successivo all'ingresso della Cina nella WTO.",
    education: ["Laurea in Giurisprudenza - Università degli Studi di Roma Tre (2013)"],
    languages: ["Italiano"],
    imageUrl: "",
    orderIndex: 17,
  },
  {
    id: "22",
    name: "Avv. Lorenzo Ferrara",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-penale", "corporate-compliance", "diritto-tributario", "crisi-impresa", "diritto-assicurazioni", "diritto-sanitario"],
    office: "Roma",
    email: "l.ferrara@legalit.it",
    pec: "l.ferrara@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    fullBio: "Lorenzo Ferrara si occupa prevalentemente di diritto penale, con specifica esperienza sia in ambito giudiziale sia nell'attività di consulenza penal-preventiva d'impresa. In ambito giudiziale ha maturato significativa esperienza nei reati tributari, fallimentari, societari, contro la P.A., contro il patrimonio e ambientali. In ambito consulenziale ha maturato significativa esperienza in diritto penale di impresa e compliance aziendale, con focus sulla responsabilità degli enti ex d.lgs. 231/01 e sulla normativa anticorruzione, antiriciclaggio e privacy, contribuendo al costante monitoraggio delle novità normative in materia ed alla redazione e aggiornamento di modelli di organizzazione, gestione e controllo ex d.lgs. 231/2001 ed all'implementazione di progetti di compliance integrata.\n\nÈ membro di Organismi di Vigilanza ex d.lgs. 231/01 di società operanti in diversi settori produttivi.\n\nHa conseguito il Master breve Diritto Penale d'Impresa presso Medichini Clodio Formazione nel 2022 e ha partecipato al ciclo di seminari La difesa tributaria dal tributario al processo penale tenuto dall'Associazione Centro di Diritto Penale Tributario nel 2024.\n\nDopo la laurea, conseguita presso l'Università degli Studi di Roma Tre con una tesi in diritto costituzionale regionale dal titolo \"Il dialogo tra amministrazioni nella fase governativa del controllo di legittimità costituzionale delle leggi regionali\", ha maturato una prima esperienza nel diritto civile e penale presso un affermato studio legale di Roma.\n\nNel 2017 ha lavorato presso la Presidenza del Consiglio dei Ministri – Dipartimento per gli Affari Regionali, nell'ufficio competente per il controllo di legittimità delle leggi regionali e delle relative modifiche statutarie.\n\nDal 2019 collabora con Studio Legalit.\n\nÈ avvocato dal gennaio 2022 ed è iscritto all'Ordine degli Avvocati di Roma.",
    education: ["Laurea in Giurisprudenza - Università degli Studi di Roma Tre", "Master breve Diritto Penale d'Impresa - Medichini Clodio Formazione (2022)"],
    languages: ["Italiano"],
    imageUrl: "",
    orderIndex: 18,
  },
  {
    id: "21",
    name: "Avv. Flavia Cracchiolo",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-lavoro"],
    office: "Roma",
    email: "f.cracchiolo@legalit.it",
    pec: "f.cracchiolo@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-flavia-cracchiolo.jpg",
    orderIndex: 19,
  },
  {
    id: "23",
    name: "Avv. Sabrina Causa",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "s.causa@legalit.it",
    pec: "sabrinacausa@pecavvpa.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-sabrina-causa.jpg",
    orderIndex: 20,
  },
  {
    id: "24",
    name: "Avv. Paola Saladino",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "p.saladino@legalit.it",
    pec: "paolasaladino@pecavvpa.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-paola-saladino.jpg",
    orderIndex: 21,
  },
  {
    id: "25",
    name: "Avv. Luciana Maria Russo",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "l.russo@legalit.it",
    pec: "lucianarusso0605@pec.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-luciana-maria-russo.jpg",
    orderIndex: 22,
  },
  {
    id: "26",
    name: "Avv. Calogero Gianluca Rizzuto",
    title: "Senior Associate",
    role: "Senior Associate",
    specializations: ["diritto-penale", "corporate-compliance", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "c.rizzuto@legalit.it",
    pec: "calogerorizzuto@pecavvpa.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "",
    orderIndex: 23,
  },
  {
    id: "27",
    name: "Avv. Riccardo Costa",
    title: "Associate",
    role: "Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "r.costa@legalit.it",
    pec: "costa.riccard@pec.it",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-riccardo-costa.jpg",
    orderIndex: 24,
  },
  {
    id: "28",
    name: "Avv. Alessandro Maria Miliziano",
    title: "Associate",
    role: "Associate",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "a.miliziano@legalit.it",
    pec: "",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-alessandro-miliziano.jpg",
    orderIndex: 25,
  },
  {
    id: "29",
    name: "Dott. Marco Pauletti",
    title: "Trainee",
    role: "Trainee",
    specializations: ["diritto-penale", "corporate-compliance"],
    office: "Roma",
    email: "m.pauletti@legalit.it",
    pec: "m.pauletti@ordineavvocatiroma.org",
    phone: "+39 06 3213911",
    fullBio: "Marco Pauletti si occupa prevalentemente di diritto penale, diritto penale di impresa e compliance aziendale (con particolare riferimento alla responsabilità degli enti ex d.lgs. 231/01), contribuendo al costante monitoraggio delle novità normative in materia ed alla redazione e aggiornamento di modelli di organizzazione, gestione e controllo ex d.lgs. 231/2001 ed all'implementazione di progetti di compliance integrata.\n\nSubito dopo la Laurea e sino al 2025, ha maturato la sua prima esperienza nel diritto penale presso uno studio legale di Roma.\n\nDal 2025 collabora con lo Studio Legalit.\n\nSi è laureato nel 2022 presso l'Università LUISS Guido Carli di Roma, discutendo una tesi dal titolo \"Il Progetto preliminare di Codice penale di Enrico Ferri: profili critico-storici e sviluppo della sociologia criminale in Italia\".\n\nHa collaborato con la rubrica del Sole24ore Diritto+ scrivendo contributi in materia penale e dal 2023 collabora stabilmente con la testata \"ItaliaOggi\" e con la Rivista scientifica \"Ambiente&Sicurezza\", per la quale è autore di numerosi articoli in materia di Sicurezza sul lavoro (D.Lgs. 81/2008).\n\nÈ iscritto all'Ordine degli Avvocati Praticanti di Roma.\n\nParla l'inglese.",
    education: ["Laurea in Giurisprudenza - Università LUISS Guido Carli di Roma"],
    languages: ["Italiano", "Inglese"],
    imageUrl: "",
    orderIndex: 26,
  },
  {
    id: "30",
    name: "Dott. Angela Martina Tortorici",
    title: "Trainee",
    role: "Trainee",
    specializations: ["diritto-amministrativo", "diritto-civile-commerciale"],
    office: "Palermo",
    email: "m.tortorici@legalit.it",
    pec: "",
    phone: "+39 091 8680254",
    education: [],
    languages: ["Italiano"],
    imageUrl: "/attached_assets/avv-angela-martina-tortorici.jpg",
    orderIndex: 27,
  },
];

export const values = [
  {
    title: "Eccellenza Legale",
    description: "Assistenza legale di qualità superiore basata su competenza ed esperienza pluridecennale.",
  },
  {
    title: "Approccio Multidisciplinare",
    description: "Team di professionisti specializzati in diverse aree del diritto per soluzioni complete.",
  },
  {
    title: "Integrità e Trasparenza",
    description: "Rapporto di fiducia costruito sulla chiarezza e onestà professionale.",
  },
  {
    title: "Innovazione Continua",
    description: "Aggiornamento costante su normative e tecnologie per servizi all'avanguardia.",
  },
];
